insert into CUSTOMER (ID , NAME ,LAST_NAME) VALUES (1,'HARSH','PATIL');
insert into CUSTOMER (ID , NAME ,LAST_NAME) VALUES (2,'RUSHI','PATIL');
insert into CUSTOMER (ID , NAME ,LAST_NAME) VALUES (3,'VISHWAJEET','PATIL');